easy_admin:
    design:
        form_theme: '@EasyAdmin/form/bootstrap_4.html.twig'
        
    entities:
        # List the entity class name you want to manage
        User:
            class: App\Entity\User
            label: 'Пользователи'
            list:
                fields:
                    - id    
                    - {property: name, label: 'Имя'}
                    - {property: email, label: 'Эл.почта'}
                    - {property: phone, label: 'Телефон'}
                    - {property: createdAt, label: 'Дата регистрации'}
                    - {property: ads, label: 'Кол-во объявлений'}
            form:
                fields:
                    - {property: name, label: 'Имя'}
                    - {property: email, label: 'Эл.почта'}
                    - {property: phone, label: 'Телефон'}
                    - {property: ads, label: 'Объявления'}
        Category:
            class: App\Entity\Category
            label: 'Категории'
            list:
                fields:
                    - id    
                    - {property: name, label: 'Название категории'}
                    - {property: products, label: 'Кол-во товаров'}
            form:
                fields:
                    - {property: name, label: 'Название категории'}
                    
        Product:
            class: App\Entity\Product
            label: 'Товары'
            list:
                fields:
                    - id
                    - {property: 'enabled', label: 'В продаже'}
                    - {property: 'photos[0].image', label: 'Фото', type: 'image', base_path: '%app.path.product_images%'}
                    - {property: 'name', label: 'Название'}
                    - {property: 'category', label: 'Категория'}
                    - {property: 'price', label: 'Цена', type: 'string'}
                    - {property: 'description', label: 'Описание'}
                    - {property: 'dateAt', label: 'Опубликован'}
                    - {property: 'location', label: 'Регион'}
                    - {property: 'user.email', label: 'Владелец', type: 'email'}
            show:
                title: '%%entity_label%% (#%%entity_id%%)'
            form: 
                fields:
                    - {property: 'name', label: 'Название'}
                    - {property: 'category', label: 'Категория'}
                    - {property: 'enabled', label: 'В продаже'}
                    - {property: 'price', label: 'Цена'}
                    - {property: 'description', label: 'Описание'}
                    - {property: 'location', label: 'Регион'}
                    - {property: 'photos', label: 'Фото'}
                    - photos
                    
        Ad:
            class: App\Entity\Ad
            label: 'Объявления'
            list:
                dql_filter: 'entity.enabled != false'
                fields:
                    - id
                    - {property: 'enabled', label: 'Опубликован'}
                    - {property: 'photos[0].image', label: 'Фото', type: 'image', base_path: '%ads_images%'}
                    - {property: 'name', label: 'Название'}
                    - {property: 'price', label: 'Цена', type: 'string'}
                    - {property: 'description', label: 'Описание'}
                    - {property: 'dateAt', label: 'Время публикации'}
                    - {property: 'location', label: 'Регион'}
                    - {property: 'user.email', label: 'Владелец', type: 'email'}
            show:
                title: '%%entity_label%% (#%%entity_id%%)'
            form: 
                fields:
                    - {property: 'name', label: 'Название'}
                    - {property: 'enabled', label: 'Опубликован'}
                    - {property: 'price', label: 'Цена'}
                    - {property: 'description', label: 'Описание'}
                    - {property: 'location', label: 'Регион'}
                    - {property: 'photos', label: 'Фото'}      
        Ads_disabled:
            class: App\Entity\Ad
            label: 'На утверждении'
            list:
                dql_filter: 'entity.enabled != true'
                fields:
                    - id
                    - {property: 'enabled', label: 'Опубликован'}
                    - {property: 'photos[0].image', label: 'Фото', type: 'image', base_path: '%ads_images%'}
                    - {property: 'name', label: 'Название'}
                    - {property: 'price', label: 'Цена', type: 'string'}
                    - {property: 'description', label: 'Описание'}
                    - {property: 'dateAt', label: 'Время публикации'}
                    - {property: 'location', label: 'Регион'}
                    - {property: 'user.email', label: 'Владелец', type: 'email'}
            show:
                title: '%%entity_label%% (#%%entity_id%%)'
            form: 
                fields:
                    - {property: 'name', label: 'Название'}
                    - {property: 'enabled', label: 'Опубликован'}
                    - {property: 'price', label: 'Цена'}
                    - {property: 'description', label: 'Описание'}
                    - {property: 'location', label: 'Регион'}
                    - {property: 'photos', label: 'Фото'}      
                    
        Photo_ads:
            class: App\Entity\Photo
            label: 'Фотографии объявлений'
            form: 
                fields:
                    - {property: 'product', label: 'Название товара', type: 'text'}
                    - {property: 'imageFile', label: 'Фото', type: 'file'}

            list:
                dql_filter: 'entity.ad > 0'
                fields:
                    - ad
                    - {property: 'image', label: 'Фото', type: 'image', base_path: '%ads_images%'}
                    - {property: 'ad.name', label: 'Название объявления', type: 'text'}
                    - {property: 'ad.user', label: 'Автор', type: 'text'}
                    
        Photo:
            class: App\Entity\Photo
            label: 'Фотографии запчастей'
            form: 
                fields:
                    - product
                    - {property: 'imageFile', label: 'Фото', type: 'file'}

            list:
                dql_filter: 'entity.product >= 0 OR (entity.product IS NULL AND entity.ad IS NULL)'
                fields:
                    - id
                    - {property: 'image', label: 'Фото', type: 'image', base_path: '%app.path.product_images%'}
                    - {property: 'product', label: 'Название товара', type: 'text'}
         
        
        
